@email=rosdfasd@asdas.tea
@password=asddt!ddd3rass11asasdas12312


### register
# @name postRegister
POST http://127.0.0.1:7000/register
Content-Type: application/json

{
    "email": "rosdfasd@asdas.tea",
    "password": "asddt!ddd3rass11asasdas12312"
}



### login
# @name postLogin
POST http://127.0.0.1:7000/login
Content-Type: application/json

{
    "email": "rosdfasd@asdas.tea",
    "password": "asddt!ddd3rass11asasdas12312"
}

###
@token = {{token}}
###

GET http://127.0.0.1:7000/users/1
Content-Type: application/json

###

GET http://127.0.0.1:7000/users/5
Content-Type: application/json

###
DELETE http://127.0.0.1:7000/users/1
Content-Type: application/json
Token: {{token}}


###

POST http://127.0.0.1:7000/ads
Content-Type: application/json
Token: {{token}}

{
    "title": "Nice title",
    "description": "Big one discription"
}

###

###

PATCH http://127.0.0.1:7000/ads/3
Content-Type: application/json
Token: {{token}}

{
    "title": "4top",
    "description": "New small disc"
}

###


GET http://127.0.0.1:7000/ads/3
Content-Type: application/json



###

DELETE http://127.0.0.1:7000/ads/3
Content-Type: application/json
Token: {{token}}


###